export let searchBtn = document.querySelector("#searchBtn")
export let menuBtn = document.querySelector("#menuBtn")
export let searchForm = document.querySelector(".searchForm")
export let navbar = document.querySelector(".navbar")
export let header = document.querySelector(".header")
export let section = document.querySelectorAll("section")
export let navLink = document.querySelectorAll(".header .navbar a")